name: API pull request
"on":
  pull_request:
    paths:
      - "backend/**"
env:
  CI: true
  MONGODB_URL: "mongodb://localhost:27017/test"

defaults:
  run:
    working-directory: "./backend"

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.7.0
        with:
          mongodb-version: "4.4"

      - name: Node Dependency Install
        run: yarn install

      - name: Run Integration Test
        run: yarn test

      - name: Run Coverage Test
        run: yarn coverage
